spring:
  application:
    name: picpaysimplificado

  datasource:
    url: jdbc:mysql://localhost:3306/picpaysimplificado?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
